__title__ = 'kodi-playing'
__version__ = '1.3.2'
__author__ = 'Arjen Balfoort'
__author_email__ = 'arjenbalfoort@hotmail.com'
__maintainer__ = ''
__maintainer_email__ = ''
__url__ = 'https://gitlab.com/abalfoort/kodi-playing'
__description__ = 'Show a notification when your Kodi server is playing a new song'
__download_url__ = 'https://gitlab.com/abalfoort/kodi-playing/-/archive/master/kodi-playing-master.tar.gz'

